lantiq: dts: add missing gpio.h header for falcon.dtsi
Fix build error:

FATAL ERROR: Syntax error parsing input tree
Lexical error: ../dts/falcon.dtsi:175.22-38 Unexpected 'GPIO_ACTIVE_HIGH'
Lexical error: ../dts/falcon.dtsi:176.15-31 Unexpected 'GPIO_ACTIVE_HIGH'

Fixes: c186d17fa518 ("treewide: replace numbers with GPIO_ACTIVE")
Signed-off-by: Shiji Yang <yangshiji66@outlook.com>
Link: https://github.com/openwrt/openwrt/pull/22915
Signed-off-by: Robert Marko <robimarko@gmail.com>